### ISSUE TITLE
Unable to build for test

### ISSUE THREAD

**Issue by moneal** [shprink/wp-api-angular#11]
It looks like the build/contribute instructions are outdated.

`npm run watch` errors  with:
```
ERROR in ./src/index.ts
Module build failed: A file specified in tsconfig.json could not be found: /Users/ghost/tmp/wp-api-angularjs/typings/overwrite.d.ts
```

and the script for `devserver` is missing from the `package.json`

I tested like 15 minutes after you pushed the 3.0.x branch up. Was super happy to see angular2 support :)

**Comment by shprink** [comment]
cool, sorry I forgot to push a file. It is now ok on develop. let me know if it works ;)

**Comment by shprink** [comment]
re run `cp config.dist.json config.json` so you will get the latest config that works with my web service.

you can use my baseurl if you do not have yours `"baseUrl": "http://dev.julienrenaux.fr/wp-json/"`

**Comment by shprink** [comment]
if you need help I am on the chat https://gitter.im/shprink/wp-api-angularjs

**Comment by moneal** [comment]
Adding the missing file fixed the problem.
