### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by connelhooley** [shprink/wp-api-angular#15]
This package's typing definitions don't appear to work correctly for me. When I use the `getList()` function Visual Studio Code actually infers it returns an `any` object. If I go to a `d.ts` in this package like the `Posts.d.ts` file I see error messages on the imports at the top of the file like this:
> [ts] An import path cannot end with a '.d.ts' extension. Consider importing 'rxjs/Observable' instead.

If I replace:
`import { Observable } from 'rxjs/Observable.d.ts';`
`import { RequestOptionsArgs } from '@angular/http/src/interfaces.d.ts';`
`import { Response } from '@angular/http/src/static_response.d.ts';`

With:
`import { Observable } from 'rxjs/Observable';`
`import { RequestOptionsArgs } from '@angular/http/src/interfaces';`
`import { Response } from '@angular/http/src/static_response';`

Then Visual Studio Code picks up the correct return type of `Observable`. Is there a reason the file extensions are given?

**Comment by shprink** [comment]
I think that's just a rule with your TypeScript linter. You should not run it on `node_modules`.

**Comment by shprink** [comment]
Can you check that? Otherwise I will release a new version with this fix ;)

**Comment by connelhooley** [comment]
Sure, I'll have a look at this when I'm next at home. I didn't actually set up the linter, I used the Angular CLI to create a project which set it all up for me, which may turn out to be quite a popular useage for your package in the future. I'll investigate some more and get back to you.

**Comment by shprink** [comment]
That's alright, will release a new version tonight ;) thanks for reporting!

**Comment by shprink** [comment]
Please try `alpha9` and let me know ;)
