### ISSUE TITLE
Get a post with slug?

### ISSUE THREAD

**Issue by klihelp** [shprink/wp-api-angular#18]
How to get a post with slug?

**Comment by shprink** [comment]
Is it even possible via WP-API?

**Comment by klihelp** [comment]
Yes, it's in the long list of supported arguments, on
http://v2.wp-api.org/reference/pages/

`eg: /wp-json/wp/v2/pages/?slug=about`

**Comment by shprink** [comment]
if it is possible then it is possible with wp-api-angular:

```
import { URLSearchParams } from '@angular/http';
export class Component {
    constructor(
        private wpApiPages: WpApiPages
    ) { }

    getPageBySlug() {
        const uRLSearchParams = new URLSearchParams();
        uRLSearchParams.set('slug', 'about');

        wpApiPages.getList(
            search: uRLSearchParams
        ).map((r) => r.json())
        .subscribe(()
    }
}

```

**Comment by malfborger** [comment]
when i do this my editor says 

severity: 'Error'
message: 'Supplied parameters do not match any signature of call target.'
