### ISSUE TITLE
Error in 3.0.0-beta4 - Cannot read property 'get' of undefined httpGet

### ISSUE THREAD

**Issue by klihelp** [shprink/wp-api-angular#20]
This error only comes up in the browser console.

```
TypeError: Cannot read property 'get' of undefined
    at WpApiPages.WpApiParent.httpGet
```

--
Using webpack based starter project: https://github.com/Websitescity/ng2-f6-starter
Worked with version 3.0.0-beta3

**Comment by shprink** [comment]
beta5 should fix the problem. please confirm

**Comment by klihelp** [comment]
Thanks you, works well:)
