### ISSUE TITLE
how to retrieve custom type posts?

### ISSUE THREAD

**Issue by malfborger** [shprink/wp-api-angular#22]
I have registered in the "right" way http://v2.wp-api.org/extending/custom-content-types/

**Comment by malfborger** [comment]
I have registered in the "right" way http://v2.wp-api.org/extending/custom-content-types/

**Comment by shprink** [comment]
```
let instance = wpApiCustom.getInstance('cars');
```

then on instance you have the following methods:

```
  getList(taxonomiesType: string, options?: RequestOptionsArgs): Observable<Response>;
  get(taxonomiesType: string, termId: number, options?: RequestOptionsArgs): Observable<Response>;
  create(taxonomiesType: string, body: any, options?: RequestOptionsArgs): Observable<Response>;
  update(taxonomiesType: string, termId: number, body: any, options?: RequestOptionsArgs): Observable<Response>;
  delete(taxonomiesType: string, termId: number, options?: RequestOptionsArgs): Observable<Response>;
```

**Comment by mattbag** [comment]
Hello,
on this method the uRLSearchParams don't seem to be working (for me)
This is how I set it, inside a provider fn:

`  const uRLSearchParams = new URLSearchParams();
      uRLSearchParams.set('category', category.toLocaleLowerCase().replace(' ', '_'));
        uRLSearchParams.set('posts_per_page', '20');
         let instance = this.wpApiCustom.getInstance('products');
    return instance.getList( { search: uRLSearchParams})`

What I get is all the post of the correct type, stopping at 100, no filter per category.
I tried also 'per_page' but no changes
Where's the mistake? Cheers

**Comment by shprink** [comment]
`per_page` should work. Checkout the docs: https://developer.wordpress.org/rest-api/reference/posts/
