### ISSUE TITLE
/ccf/v1/forms 403 rest_forbidden

### ISSUE THREAD

**Issue by metazoa-org** [shprink/wp-api-angular#25]
Not logged user cannot get /ccf/v1/forms nor /ccf/v1/forms/$id even if "Require User to Be Logged In" is set to "no".

**Comment by shprink** [comment]
what is `/ccf/v1/forms` ?

**Comment by metazoa-org** [comment]
ahh, sorry. This should be open here: https://github.com/tlovett1/custom-contact-forms. Sorry for the mistake.
