### ISSUE TITLE
Angular version requirement and angular.merge

### ISSUE THREAD

**Issue by kynetiv** [shprink/wp-api-angular#5]
I am trying to upgrade my use of the WP-API to v2 and related angular client to your project and was noticing some `angular.merge` is not defined errors. Looks like the merge method was added around the <a href="https://github.com/angular/angular.js/blob/master/CHANGELOG.md#140-jaracimrman-existence-2015-05-26">Angular 1.4 release</a> and my angular version was not late enough. Might want to add that this module depends on angular > 1.3. or maybe a workaround with `angular.extend` .

**Comment by shprink** [comment]
You are right Angular 1.4 is needed. I could try to find a workaround and use angular.extend if it is not a deep extend.

**Comment by shprink** [comment]
angular v1 version will not evolve anymore. Angular2 version will
