### ISSUE TITLE
Issues with Bower implementation

### ISSUE THREAD

**Issue by davidrhoderick** [shprink/wp-api-angular#8]
Currently there are the following issues with Bower implementation:

1. `main` is not defined.  That means that when you are using automated tasks such as grunt-contrib-wiredep, the actual script will not be included in compilations.  Had to add it manually.
2. Restangular is not added as a dependency, which it is.  This means `bower install` won't actually install  all dependencies needed.
3. Underscore isn't included in the bundle.js file.

I actually didn't even successfully implement the library because of these problems and because WpiApiProvider.setBaseURL is not working correctly; it isn't interpreted as a function but as a variable.

**Comment by shprink** [comment]
I guess you must have install v1 instead of v2. Bower is not supported, only npm is. 

If you find out the right way to use it with bower PR are welcome.

Thanks

**Comment by shprink** [comment]
Bower is not support in v3 either. closing
