### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by tdatu** [shprink/wp-api-angular#9]
Hi, 
is this compatible with Angular 2?
Thanks!

**Comment by shprink** [comment]
not yet but it is planned ;)

**Comment by tdatu** [comment]
hurry up! angular 2 devs are suffering.. :)
thanks for prompt reply.

**Comment by tdatu** [comment]
closing this issue. thanks for your work!

**Comment by shprink** [comment]
it has started https://github.com/shprink/wp-api-angularjs/tree/ng2

**Comment by shprink** [comment]
you can follow the updates here https://github.com/shprink/wp-api-angularjs/pull/10

**Comment by tdatu** [comment]
Awesome! You're a beast!
